# site settings
title: "Francesco Santoro De Vico Portfolio"
description: "Benvenuti nel mio portfolio. Scopri di più su di me, i miei hobby e le mie passioni."
baseurl: "" # Lascia vuoto per il sito principale
url: "https://fsdv.eu" # URL del tuo sito
github_username: "PacoSanto"
markdown: kramdown
theme: minima

author:
street_address: Cuesta de alhacaba 7 y 9
city: Granada
zip_code: 18010
country: Spain
phone: (+39) 3200108001
socials:
  GitHub: https://github.com/PacoSanto
  LinkedIn: https://www.linkedin.com/in/francesco-santoro-geo

# Configurazione delle sezioni del sito
sections:
  - name: "About"
    url: "/about.html"
  - name: "News"
    url: "/news.html"
  - name: "University"
    url: "/university.html"
    subsections:
      - name: "CV"
        url: "/cv.html"
      - name: "Community"
        url: "/community.html"
      - name: "About My Research"
        url: "/about-my-research.html"
  - name: "Passion"
    url: "/passion.html"
    subsections:
      - name: "Music"
        url: "/music.html"
      - name: "Football"
        url: "/football.html"
      - name: "Photography"
        url: "/photography.html"
      - name: "Other"
        url: "/other.html"
  - name: "Contact"
    url: "/contact.html"

# Forty theme settings
intro: "Welcome to Francesco Santoro De Vico portfolio website. Explore my work, my hobbies, and learn more about me."
header_image: "assets/images/header.jpg" # Path to your header image
