title: "Il Mio Portfolio"
description: "Il mio sito portfolio utilizzando Forty Jekyll"
baseurl: ""
url: "http://fsdv.eu.com"
github_username: "PacoSanto"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Author settings
author:
  name: "Francesco Santoro De Vico"
  email: "francesco.santoro.geologo@gmail.com"

# Social links
social:
  github: https://github.com/PacoSanto

# Default values
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: "Francesco Santoro De Vico"
